---

- name: FATAL
  ansible.builtin.fail:
    msg: "This role is only compatible with Darwin/MacOS"
  when: ansible_os_family != 'Darwin'

- name: Import travis
  ansible.builtin.import_tasks: travis.yml

- name: Import darwin
  ansible.builtin.import_tasks: darwin.yml
